apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: Security
  name: Security
  labels:
    app: Security
spec:
  selector:
    matchLabels:
      app: Security
  template:
    metadata:
      labels:
        app: Security
        name: Security
    spec:
      containers:
        - name: Security
          image: azar-intelops/records-db-web-api/Security
          imagePullPolicy: Always
          ports:
        
          - containerPort: 8080
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        