apiVersion: v1
kind: Service
metadata:
  namespace: Security
  labels:
    app: Security
  name: Security
spec:
  ports:
  
    - protocol: TCP
      port: 8080
      targetPort: 8080
   
  selector:
    app: Security
  type: ClusterIP
