apiVersion: v1
kind: Service
metadata:
  namespace: NormalizeAddress
  labels:
    app: NormalizeAddress
  name: NormalizeAddress
spec:
  ports:
  
    - protocol: TCP
      port: 8084
      targetPort: 8084
   
  selector:
    app: NormalizeAddress
  type: ClusterIP
