apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: DatabaseLicenseInfo
  name: DatabaseLicenseInfo
  labels:
    app: DatabaseLicenseInfo
spec:
  selector:
    matchLabels:
      app: DatabaseLicenseInfo
  template:
    metadata:
      labels:
        app: DatabaseLicenseInfo
        name: DatabaseLicenseInfo
    spec:
      containers:
        - name: DatabaseLicenseInfo
          image: azar-intelops/records-db-web-api/DatabaseLicenseInfo
          imagePullPolicy: Always
          ports:
        
          - containerPort: 8081
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        