apiVersion: v1
kind: Service
metadata:
  namespace: DatabaseLicenseInfo
  labels:
    app: DatabaseLicenseInfo
  name: DatabaseLicenseInfo
spec:
  ports:
  
    - protocol: TCP
      port: 8081
      targetPort: 8081
   
  selector:
    app: DatabaseLicenseInfo
  type: ClusterIP
