apiVersion: v1
kind: Service
metadata:
  namespace: DefaultRecordDbdataConfiguration
  labels:
    app: DefaultRecordDbdataConfiguration
  name: DefaultRecordDbdataConfiguration
spec:
  ports:
  
    - protocol: TCP
      port: 8082
      targetPort: 8082
   
  selector:
    app: DefaultRecordDbdataConfiguration
  type: ClusterIP
